CREATE TABLE T_CM_PAIS (
  id_pais INT PRIMARY KEY,
  nm_pais VARCHAR(50) NOT NULL
);

CREATE TABLE T_CM_ESTADO (
  id_estado INT PRIMARY KEY,
  id_pais INT REFERENCES T_CM_PAIS(id_pais),
  nm_estado VARCHAR(50) NOT NULL
);

CREATE TABLE T_CM_CIDADE (
  id_cidade INT PRIMARY KEY,
  id_estado INT REFERENCES T_CM_ESTADO(id_estado),
  nm_cidade VARCHAR(50) NOT NULL
);

CREATE TABLE T_CM_BAIRRO (
  id_bairro INT PRIMARY KEY,
  id_cidade INT REFERENCES T_CM_CIDADE(id_cidade),
  nm_bairro VARCHAR(100) NOT NULL
);

CREATE TABLE T_CM_LOGRADOURO (
  id_logradouro INT PRIMARY KEY,
  id_bairro INT REFERENCES T_CM_BAIRRO(id_bairro),
  nm_logradouro VARCHAR(100) NOT NULL,
  nr_logradouro VARCHAR(10) NOT NULL,
  nm_complemento VARCHAR(100)
);

CREATE TABLE T_CM_CLIENTE (
  id_cliente INT PRIMARY KEY,
  id_logradouro INT REFERENCES T_CM_LOGRADOURO(id_logradouro),
  nm_cliente VARCHAR(100) NOT NULL,
  nr_cpf VARCHAR(14) UNIQUE NOT NULL,
  nm_email VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE T_CM_MODELO (
  id_modelo INT PRIMARY KEY,
  nm_modelo VARCHAR(100) NOT NULL
);

CREATE TABLE T_CM_FILIAL_DEPARTAMENTO (
  id_filial_departamento BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nm_filial_departamento VARCHAR(100) NOT NULL
);

CREATE TABLE T_CM_MOTO (
  id_moto INT PRIMARY KEY,
  id_modelo INT NOT NULL,
  id_filial_departamento BIGINT NOT NULL, -- ajustado para BIGINT
  nm_placa VARCHAR(10) NOT NULL UNIQUE,
  st_moto VARCHAR(30),
  km_rodado INT,
  CONSTRAINT fk_moto_modelo FOREIGN KEY (id_modelo) REFERENCES T_CM_MODELO(id_modelo),
  CONSTRAINT fk_moto_filial FOREIGN KEY (id_filial_departamento) REFERENCES T_CM_FILIAL_DEPARTAMENTO(id_filial_departamento)
);

CREATE TABLE T_CM_ALUGUEL (
  id_aluguel INT PRIMARY KEY,
  id_cliente INT NOT NULL,
  id_moto INT NOT NULL,
  dt_retirada TIMESTAMP NOT NULL,
  dt_devolucao TIMESTAMP,
  CONSTRAINT fk_aluguel_cliente FOREIGN KEY (id_cliente) REFERENCES T_CM_CLIENTE(id_cliente),
  CONSTRAINT fk_aluguel_moto FOREIGN KEY (id_moto) REFERENCES T_CM_MOTO(id_moto)
);

CREATE TABLE T_CM_POSICAO_MOTO (
  id_posicao INT PRIMARY KEY,
  id_filial_departamento BIGINT NOT NULL, -- ajustado para BIGINT
  nr_x DECIMAL(8,2) NOT NULL,
  nr_y DECIMAL(8,2) NOT NULL,
  nm_setor VARCHAR(50),
  dt_posicao TIMESTAMP,
  CONSTRAINT fk_posicao_filial FOREIGN KEY (id_filial_departamento) REFERENCES T_CM_FILIAL_DEPARTAMENTO(id_filial_departamento)
);

CREATE TABLE T_CM_MANUTENCAO (
  id_manutencao INT PRIMARY KEY,
  id_moto INT NOT NULL,
  dt_entrada TIMESTAMP NOT NULL,
  dt_saida TIMESTAMP,
  ds_manutencao VARCHAR(300),
  CONSTRAINT fk_manutencao_moto FOREIGN KEY (id_moto) REFERENCES T_CM_MOTO(id_moto)
);

CREATE TABLE T_CM_IMAGEM_REGISTRO (
  id_imagem_registro INT PRIMARY KEY,
  id_posicao INT NOT NULL,
  dt_imagem TIMESTAMP NOT NULL,
  nm_caminho_arquivo VARCHAR(255) NOT NULL,
  CONSTRAINT fk_imagem_posicao FOREIGN KEY (id_posicao) REFERENCES T_CM_POSICAO_MOTO(id_posicao)
);

CREATE TABLE T_CM_SENSOR_RFID (
  id_sensor INT PRIMARY KEY,
  nm_sensor VARCHAR(100) NOT NULL,
  id_filial_departamento BIGINT NOT NULL, -- ajustado para BIGINT
  nm_localizacao VARCHAR(100),
  CONSTRAINT fk_sensor_filial FOREIGN KEY (id_filial_departamento) REFERENCES T_CM_FILIAL_DEPARTAMENTO(id_filial_departamento)
);

CREATE TABLE T_CM_LOCALIZACAO_MOTO_RFID (
  id_localizacao INT PRIMARY KEY,
  id_moto INT NOT NULL,
  id_sensor INT NOT NULL,
  dt_localizacao TIMESTAMP NOT NULL,
  CONSTRAINT fk_localizacao_moto FOREIGN KEY (id_moto) REFERENCES T_CM_MOTO(id_moto),
  CONSTRAINT fk_localizacao_sensor FOREIGN KEY (id_sensor) REFERENCES T_CM_SENSOR_RFID(id_sensor)
);
